runtime: python39  # Gunakan runtime sesuai kebutuhan

handlers:
- url: /  # Menangani root URL (halaman utama)
  static_files: index.html
  upload: index.html

- url: /styles.css  # Menangani file CSS
  static_files: styles.css
  upload: styles.css

- url: /(.*)  # Menangani file statis lainnya, seperti gambar
  static_files: \1
  upload: .*
